### PR TITLE
Fix little button style issue

### PR DESCRIPTION
**Pull request by osamajandali**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks! This branch should be [rebased onto master](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch).

**Comment by osamajandali** [comment]
Rebased

**Comment by kentcdodds** [comment]
Sorry, could you update your branch to the current `master` branch again? I pushed updates so everything should be working now :) Thanks!

**Comment by osamajandali** [comment]
The branch is up to date, do you mean to merge my branch to master ?

**Comment by kentcdodds** [comment]
Sorry, no I don't think your branch is up to date. If you look at this PR you'll see it has a number of old commits as well as more changes than I think you intend on including. This might help: https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repository and then this https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch

**Comment by osamajandali** [comment]
Yeah I'm sorry I thought that the rebase has been done. I fix it now

**Pull request merged**
